project_id = "qxkeungqbgaytxdfhccn"

[functions.send-contact]
verify_jwt = false

[functions.generate-ideas]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.generate-budget-pdf]
verify_jwt = false
